name: Alex Liao (On Cloud)
# avatar: images/profile.png # Avatar image. Default to "images/profile.webp".
bio: 'Full Stack Engineer.'
company: Company # HTML markup are supported, such as: <a href="https://example.com" target="_blank" rel="noopener noreferrer">Company</a>.
location: Earth # HTML markup are supported, such as: <a href='https://www.openstreetmap.org/search?query=Earth'>Earth</a>.
# about: https://razonyang.com # The external about page. The internal about page will be used if not set.
params: {
  # layout: compact
}
# See https://hbs.razonyang.com/v1/en/docs/widgets/social-links/.
social:
  email: oncloud@lazco.dev
  github: https://github.com/OnCloud125252
  # twitter: razonyang
  # patreon: razonyang
  # paypal: razonyang
  rss: "" # Remove RSS
  discord: https://discord.com/users/755269122597585018